# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'mainwindow.ui'
#
# Created by: PyQt5 UI code generator 5.9.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(800, 600)
        MainWindow.setWindowTitle("YAIPT!")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("images/yaipt.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        MainWindow.setWindowIcon(icon)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.centralwidget)
        self.horizontalLayout.setSizeConstraint(QtWidgets.QLayout.SetMaximumSize)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.verticalLayout1 = QtWidgets.QVBoxLayout()
        self.verticalLayout1.setSizeConstraint(QtWidgets.QLayout.SetMaximumSize)
        self.verticalLayout1.setObjectName("verticalLayout1")
        self.horizontalLayout.addLayout(self.verticalLayout1)
        self.verticalLayout2 = QtWidgets.QVBoxLayout()
        self.verticalLayout2.setSizeConstraint(QtWidgets.QLayout.SetMaximumSize)
        self.verticalLayout2.setObjectName("verticalLayout2")
        self.horizontalLayout.addLayout(self.verticalLayout2)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 800, 27))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.toolbar = QtWidgets.QToolBar(MainWindow)
        self.toolbar.setWindowTitle("")
        self.toolbar.setToolButtonStyle(QtCore.Qt.ToolButtonTextOnly)
        self.toolbar.setObjectName("toolbar")
        MainWindow.addToolBar(QtCore.Qt.TopToolBarArea, self.toolbar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.actionOpen = QtWidgets.QAction(MainWindow)
        self.actionOpen.setText("Open")
        self.actionOpen.setObjectName("actionOpen")
        self.actionDFT = QtWidgets.QAction(MainWindow)
        self.actionDFT.setText("DFT")
        self.actionDFT.setObjectName("actionDFT")
        self.actionHelp = QtWidgets.QAction(MainWindow)
        self.actionHelp.setText("Help")
        self.actionHelp.setObjectName("actionHelp")
        self.actionSave = QtWidgets.QAction(MainWindow)
        self.actionSave.setText("Save")
        self.actionSave.setObjectName("actionSave")
        self.actionPlane = QtWidgets.QAction(MainWindow)
        self.actionPlane.setText("Plane")
        self.actionPlane.setObjectName("actionPlane")
        self.actionEqualize = QtWidgets.QAction(MainWindow)
        self.actionEqualize.setText("Equalize")
        self.actionEqualize.setObjectName("actionEqualize")
        self.actionDenoise = QtWidgets.QAction(MainWindow)
        self.actionDenoise.setText("Denoise")
        self.actionDenoise.setObjectName("actionDenoise")
        self.actionInterpolate = QtWidgets.QAction(MainWindow)
        self.actionInterpolate.setText("Interpolate")
        self.actionInterpolate.setObjectName("actionInterpolate")
        self.actionButterworth = QtWidgets.QAction(MainWindow)
        self.actionButterworth.setText("Butterworth")
        self.actionButterworth.setObjectName("actionButterworth")
        self.actionCanny = QtWidgets.QAction(MainWindow)
        self.actionCanny.setText("Canny")
        self.actionCanny.setObjectName("actionCanny")
        self.actionMorphology = QtWidgets.QAction(MainWindow)
        self.actionMorphology.setText("Morphology")
        self.actionMorphology.setObjectName("actionMorphology")
        self.toolbar.addAction(self.actionOpen)
        self.toolbar.addAction(self.actionSave)
        self.toolbar.addAction(self.actionPlane)
        self.toolbar.addAction(self.actionEqualize)
        self.toolbar.addAction(self.actionDenoise)
        self.toolbar.addAction(self.actionInterpolate)
        self.toolbar.addAction(self.actionDFT)
        self.toolbar.addAction(self.actionButterworth)
        self.toolbar.addAction(self.actionCanny)
        self.toolbar.addAction(self.actionMorphology)
        self.toolbar.addAction(self.actionHelp)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        pass

